import Head from 'next/head'
import List from '../src/List'
import { FirebaseContext } from '../src/Firebase'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Wish List App
        </h1>
        <FirebaseContext.Consumer>
          {firebase => <List firebase={firebase}/>}
        </FirebaseContext.Consumer>
      </main>

      <footer className="footer">
        hello
      </footer>
    </div>
  )
}
